# Generated by Codex on 2026-05-05

from secrets import choice

import circles.models
from django.db import migrations, models


JOIN_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def generate_join_code():
    return "".join(choice(JOIN_CODE_ALPHABET) for _ in range(8))


def populate_join_codes(apps, schema_editor):
    Circle = apps.get_model("circles", "Circle")
    used_codes = set(Circle.objects.exclude(join_code="").values_list("join_code", flat=True))
    for circle in Circle.objects.filter(join_code=""):
        code = generate_join_code()
        while code in used_codes:
            code = generate_join_code()
        used_codes.add(code)
        circle.join_code = code
        circle.save(update_fields=["join_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_feedreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="join_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.RunPython(populate_join_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="circle",
            name="join_code",
            field=models.CharField(default=circles.models.generate_join_code, max_length=12, unique=True),
        ),
    ]
