# Generated by Django 5.2.1 on 2026-05-11 11:11

from django.db import migrations, models


def rename_contributor_role(apps, schema_editor):
    CircleMember = apps.get_model("circles", "CircleMember")
    CircleMember.objects.filter(role="contributor").update(role="caregiver")


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_circle_join_code'),
    ]

    operations = [
        migrations.RunPython(rename_contributor_role, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='circlemember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('caregiver', 'Caregiver'), ('viewer', 'View-only')], default='viewer', max_length=20),
        ),
    ]
