# Generated by Django 5.2.16 on 2026-07-11 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu')], default='en', max_length=16)),
                ('fallback_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu')], default='en', max_length=16)),
                ('senior_mode', models.BooleanField(default=False)),
                ('simplified_dashboard', models.BooleanField(default=False)),
                ('large_text', models.CharField(choices=[('standard', 'Standard'), ('large', 'Large'), ('extra_large', 'Extra large')], default='standard', max_length=32)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('voice_summaries', models.BooleanField(default=False)),
                ('read_aloud_reports', models.BooleanField(default=False)),
                ('assistant_voice_input', models.BooleanField(default=False)),
                ('one_click_actions', models.JSONField(blank=True, default=list)),
                ('localization_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='LocalizedContentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('report', 'Report'), ('prescription', 'Prescription'), ('assistant', 'Assistant'), ('doctor_summary', 'Doctor summary'), ('lifestyle_plan', 'Lifestyle plan')], max_length=40)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu')], max_length=16)),
                ('fallback_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu')], default='en', max_length=16)),
                ('original_text', models.TextField()),
                ('localized_text', models.TextField()),
                ('literacy_level', models.CharField(default='simple', max_length=80)),
                ('quality_checks', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='multilingual-accessibility-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_content_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'source_type'], name='accessibili_owner_i_7801d0_idx'), models.Index(fields=['owner', 'language'], name='accessibili_owner_i_d727c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoiceSummaryArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_type', models.CharField(choices=[('report_read_aloud', 'Report read aloud'), ('assistant_response', 'Assistant response'), ('doctor_summary', 'Doctor summary'), ('emergency_profile', 'Emergency profile')], max_length=40)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu')], max_length=16)),
                ('script_text', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('provider_status', models.CharField(default='planned', max_length=80)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_summary_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'voice_type'], name='accessibili_owner_i_d8e628_idx'), models.Index(fields=['owner', 'language'], name='accessibili_owner_i_6362a1_idx')],
            },
        ),
    ]
