# Generated by Django 5.2.16 on 2026-07-11 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('report_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('report', 'Report'), ('prescription', 'Prescription'), ('symptom', 'Symptom'), ('medicine', 'Medicine'), ('doctor_summary', 'Doctor summary'), ('journal', 'Journal')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('event_date', models.DateField()),
                ('source_type', models.CharField(blank=True, max_length=80)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to=settings.AUTH_USER_MODEL)),
                ('report_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='report_analysis.reportanalysis')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'event_date'], name='health_tren_owner_i_ec4a6c_idx'), models.Index(fields=['owner', 'event_type'], name='health_tren_owner_i_5e18b6_idx'), models.Index(fields=['owner', 'source_type', 'source_id'], name='health_tren_owner_i_0940e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'source_type', 'source_id', 'event_type'), name='unique_timeline_event_source')],
            },
        ),
        migrations.CreateModel(
            name='TrendInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomarker_name', models.CharField(max_length=160)),
                ('biomarker_code', models.CharField(blank=True, max_length=80)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(choices=[('improving', 'Improving'), ('worsening', 'Worsening'), ('stable', 'Stable'), ('fluctuating', 'Fluctuating'), ('insufficient_data', 'Insufficient Data')], default='insufficient_data', max_length=32)),
                ('report_count', models.PositiveSmallIntegerField(default=0)),
                ('first_value', models.FloatField(blank=True, null=True)),
                ('latest_value', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('graph_points', models.JSONField(blank=True, default=list)),
                ('risk_awareness', models.JSONField(blank=True, default=list)),
                ('doctor_prompts', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='trend-analysis-v1', max_length=40)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['biomarker_name'],
                'indexes': [models.Index(fields=['owner', 'label'], name='health_tren_owner_i_024d4c_idx'), models.Index(fields=['owner', 'biomarker_code'], name='health_tren_owner_i_b1bf6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'biomarker_name', 'biomarker_code'), name='unique_owner_biomarker_trend')],
            },
        ),
    ]
