# Generated by Django 5.2.1 on 2026-05-03 17:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=80)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('blood_test', 'blood_test'), ('lipid_panel', 'lipid_panel'), ('thyroid_panel', 'thyroid_panel'), ('urine_analysis', 'urine_analysis'), ('hba1c', 'hba1c'), ('vitamin_panel', 'vitamin_panel'), ('prescription', 'prescription'), ('xray_report', 'xray_report'), ('unknown', 'unknown')], default='unknown', max_length=40)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lab_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_ref', models.CharField(max_length=512)),
                ('structured_data_encrypted', models.JSONField(default=dict)),
                ('ai_explanation', models.JSONField(default=dict)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('bn', 'Bengali'), ('te', 'Telugu'), ('mr', 'Marathi')], default='en', max_length=5)),
                ('medications', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='StructuredParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('test_name', models.CharField(max_length=255)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('raw_value_text', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range_low', models.FloatField(blank=True, null=True)),
                ('reference_range_high', models.FloatField(blank=True, null=True)),
                ('flag', models.CharField(default='normal', max_length=20)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
