# Generated by Django 5.2.1 on 2026-05-11 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_alter_circlemember_role'),
        ('reports', '0003_reportshare'),
        ('users', '0003_lifestylelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_context', models.JSONField(default=dict)),
                ('location_payload', models.JSONField(default=dict)),
                ('summary_text', models.TextField()),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='circles.circle')),
                ('latest_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_events', to='reports.report')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyCardAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_card_accesses', to='users.familymember')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_card_accesses', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_card_accesses', to='reports.report')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='reports.emergencyevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WearableMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('steps', 'Steps'), ('sleep_minutes', 'Sleep minutes'), ('resting_heart_rate', 'Resting heart rate'), ('blood_pressure_systolic', 'Blood pressure systolic'), ('blood_pressure_diastolic', 'Blood pressure diastolic'), ('glucose', 'Glucose')], max_length=40)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('recorded_at', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='manual_import', max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-created_at'],
            },
        ),
    ]
