# Generated by Django 5.2.1 on 2026-05-12 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_emergencyevent_emergencycardaccess_wearablemetric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('short_course', 'Short course'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, default='', max_length=120)),
                ('specialty', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('medications_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_record', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionReportLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_links', to='reports.prescriptionrecord')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_links', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('prescription', 'report')},
            },
        ),
    ]
