# Generated by Django 5.2.1 on 2026-05-04 19:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(default='celebrate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='circles.activityfeedentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feed_entry', 'user')},
            },
        ),
    ]
