from django.urls import path

from reports.views import (
    EmergencyCardAccessView,
    EmergencySosView,
    GlobalChatView,
    IntegrationStatusView,
    ReportDietAdviceView,
    ReportAdherenceView,
    ReportChatView,
    ReportDetailView,
    ReportEhrExportView,
    ReportListCreateView,
    ReportShareView,
    MedicationContextView,
    PrescriptionDetailView,
    PrescriptionCandidateReportsView,
    PrescriptionContextualAnalysisView,
    PrescriptionExtractView,
    PrescriptionFromReportView,
    PrescriptionLinkView,
    PrescriptionListView,
    PrescriptionRiskAnalysisView,
    DischargeUploadView,
    PathwayRecommendationView,
    ReportSummaryView,
    ReportTrendsView,
    ReportUploadView,
    ScreeningPreviewView,
    TreatmentEffectivenessView,
    WearableMetricImportView,
)


urlpatterns = [
    path("emergency/sos", EmergencySosView.as_view()),
    path("emergency-card/<uuid:event_id>/access", EmergencyCardAccessView.as_view()),
    path("integrations/status", IntegrationStatusView.as_view()),
    path("reports", ReportListCreateView.as_view()),
    path("reports/chat", GlobalChatView.as_view()),
    path("reports/medication-context", MedicationContextView.as_view()),
    path("reports/adherence", ReportAdherenceView.as_view()),
    path("reports/prescriptions", PrescriptionListView.as_view()),
    path("reports/prescriptions/risk-analysis", PrescriptionRiskAnalysisView.as_view()),
    path("reports/prescriptions/from-report", PrescriptionFromReportView.as_view()),
    path("reports/prescriptions/<uuid:prescription_id>", PrescriptionDetailView.as_view()),
    path("reports/prescriptions/<uuid:prescription_id>/candidate-reports", PrescriptionCandidateReportsView.as_view()),
    path("reports/prescriptions/<uuid:prescription_id>/contextual-analysis", PrescriptionContextualAnalysisView.as_view()),
    path("reports/prescriptions/<uuid:prescription_id>/links", PrescriptionLinkView.as_view()),
    path("reports/prescriptions/extract", PrescriptionExtractView.as_view()),
    path("reports/discharge", DischargeUploadView.as_view()),
    path("reports/screening-preview", ScreeningPreviewView.as_view()),
    path("reports/treatment-effectiveness", TreatmentEffectivenessView.as_view()),
    path("reports/upload", ReportUploadView.as_view()),
    path("reports/trends", ReportTrendsView.as_view()),
    path("reports/<uuid:report_id>", ReportDetailView.as_view()),
    path("reports/<uuid:report_id>/chat", ReportChatView.as_view()),
    path("reports/<uuid:report_id>/diet-advice", ReportDietAdviceView.as_view()),
    path("reports/<uuid:report_id>/ehr-export", ReportEhrExportView.as_view()),
    path("reports/<uuid:report_id>/shares", ReportShareView.as_view()),
    path("reports/<uuid:report_id>/summary", ReportSummaryView.as_view()),
    path("wearables/import", WearableMetricImportView.as_view()),
    path("pathways", PathwayRecommendationView.as_view()),
]
