# Generated by Django 5.2.16 on 2026-07-11 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEducationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('content_type', models.CharField(choices=[('biomarker', 'Biomarker'), ('condition', 'Condition'), ('food', 'Food'), ('exercise', 'Exercise'), ('video', 'Video'), ('article', 'Article')], max_length=32)),
                ('audience', models.CharField(default='general', max_length=80)),
                ('summary', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_profile_fields', models.JSONField(blank=True, default=list)),
                ('medical_review_status', models.CharField(default='planned_review', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['content_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIntegrationBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('appointment', 'Appointment'), ('insurance', 'Insurance')], max_length=32, unique=True)),
                ('inbound_data', models.JSONField(blank=True, default=list)),
                ('outbound_data', models.JSONField(blank=True, default=list)),
                ('consent_required', models.BooleanField(default=True)),
                ('permission_boundary', models.TextField()),
                ('audit_events', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='planned_partner_dependency', max_length=80)),
            ],
            options={
                'ordering': ['partner_type'],
            },
        ),
        migrations.CreateModel(
            name='ChildGrowthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(blank=True, max_length=40)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('pediatrician', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_growth_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['child_name'],
            },
        ),
        migrations.CreateModel(
            name='WearableIntegrationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=120)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('sync_frequency', models.CharField(default='daily', max_length=80)),
                ('consent_scopes', models.JSONField(blank=True, default=list)),
                ('last_sync_status', models.CharField(default='planned', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_integration_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='ChildGrowthMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentile_notes', models.JSONField(blank=True, default=list)),
                ('doctor_prompts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='future_modules.childgrowthprofile')),
            ],
            options={
                'ordering': ['-measured_on', '-created_at'],
                'indexes': [models.Index(fields=['child', 'measured_on'], name='future_modu_child_i_9e04dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='FutureModuleRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('vaccination', 'Vaccination tracker'), ('womens_health', "Women's health"), ('child_growth', 'Child growth'), ('insurance', 'Insurance folder'), ('vault_expansion', 'Medical Vault expansion'), ('second_opinion', 'Second Opinion AI'), ('education', 'Health education'), ('wearables', 'Wearable integration'), ('hospitals', 'Hospital connectivity'), ('pharmacy', 'Pharmacy integration'), ('appointments', 'Appointment management'), ('nutrition', 'Nutrition planning'), ('fitness', 'Fitness recommendations'), ('mental_wellness', 'Mental wellness'), ('preventive', 'Preventive healthcare')], max_length=40)),
                ('priority', models.CharField(choices=[('now', 'Now'), ('next', 'Next'), ('later', 'Later')], default='later', max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('design_ready', 'Design ready'), ('blocked', 'Blocked')], default='planned', max_length=24)),
                ('user_value', models.TextField()),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('profile_connections', models.JSONField(blank=True, default=list)),
                ('timeline_event_types', models.JSONField(blank=True, default=list)),
                ('release_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_module_roadmap', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'module_key'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'module_key'), name='unique_owner_future_module')],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=160)),
                ('policy_number', models.CharField(max_length=120)),
                ('coverage_type', models.CharField(blank=True, max_length=120)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('emergency_claim_phone', models.CharField(blank=True, max_length=80)),
                ('document_ids', models.JSONField(blank=True, default=list)),
                ('coverage_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider_name'],
                'indexes': [models.Index(fields=['owner', 'provider_name'], name='future_modu_owner_i_b49d6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecondOpinionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.TextField()),
                ('related_document_ids', models.JSONField(blank=True, default=list)),
                ('related_timeline_event_ids', models.JSONField(blank=True, default=list)),
                ('discussion_points', models.JSONField(blank=True, default=list)),
                ('questions_to_ask', models.JSONField(blank=True, default=list)),
                ('relevant_findings', models.JSONField(blank=True, default=list)),
                ('missing_tests_to_discuss', models.JSONField(blank=True, default=list)),
                ('safety_language', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_doctor', 'Ready for doctor'), ('needs_more_info', 'Needs more information')], default='draft', max_length=32)),
                ('model_name', models.CharField(default='gemini-3.1-flash-lite', max_length=120)),
                ('prompt_version', models.CharField(default='second-opinion-safety-v1', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_opinion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='future_modu_owner_i_504736_idx')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=160)),
                ('dose_label', models.CharField(blank=True, max_length=80)),
                ('administered_on', models.DateField(blank=True, null=True)),
                ('next_due_on', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('document_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_rules', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_on', '-administered_on', 'vaccine_name'],
                'indexes': [models.Index(fields=['owner', 'next_due_on'], name='future_modu_owner_i_5eabc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WomensHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('period', 'Period'), ('pregnancy', 'Pregnancy'), ('pcos', 'PCOS'), ('menopause', 'Menopause'), ('iron', 'Iron'), ('calcium', 'Calcium')], max_length=32)),
                ('record_date', models.DateField()),
                ('cycle_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('doctor_discussion_points', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='womens_health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'record_type'], name='future_modu_owner_i_b67f60_idx')],
            },
        ),
    ]
