# Generated by Django 5.2.16 on 2026-07-11 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=160)),
                ('active_ingredient', models.CharField(max_length=160)),
                ('strength', models.CharField(blank=True, max_length=80)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('injection', 'Injection'), ('inhalation', 'Inhalation'), ('other', 'Other')], default='oral', max_length=32)),
                ('purpose', models.CharField(blank=True, max_length=240)),
                ('usage_guidance', models.TextField(blank=True)),
                ('side_effects', models.JSONField(blank=True, default=list)),
                ('food_warnings', models.JSONField(blank=True, default=list)),
                ('alcohol_warning', models.CharField(blank=True, max_length=240)),
                ('driving_warning', models.CharField(blank=True, max_length=240)),
                ('pregnancy_breastfeeding_note', models.TextField(blank=True)),
                ('duplicate_key', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=160)),
                ('timing', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reminder_status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='planned', max_length=32)),
                ('notification_plan', models.JSONField(blank=True, default=dict)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication_intelligence.medication')),
            ],
            options={
                'ordering': ['medication__sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='requested', max_length=32)),
                ('prescribed_by', models.CharField(blank=True, max_length=160)),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('safety_review_required', models.BooleanField(default=False)),
                ('safety_review_notes', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='prescription-analysis-v1', max_length=40)),
                ('source_document_reference', models.CharField(blank=True, max_length=255)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_analyses', to='documents.medicaldocument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_type', models.CharField(choices=[('allergy', 'Allergy'), ('interaction', 'Interaction'), ('duplicate', 'Duplicate'), ('expired', 'Expired'), ('food', 'Food'), ('alcohol', 'Alcohol'), ('driving', 'Driving'), ('pregnancy', 'Pregnancy'), ('general', 'General')], max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('action_prompt', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='medication_intelligence.medication')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_warnings', to='medication_intelligence.prescriptionanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medication_intelligence.prescriptionanalysis'),
        ),
        migrations.AddIndex(
            model_name='prescriptionanalysis',
            index=models.Index(fields=['owner', 'status'], name='medication__owner_i_d45afb_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionanalysis',
            index=models.Index(fields=['owner', 'is_expired'], name='medication__owner_i_781762_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionanalysis',
            index=models.Index(fields=['document', 'created_at'], name='medication__documen_a87219_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationwarning',
            index=models.Index(fields=['analysis', 'severity'], name='medication__analysi_4ee0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationwarning',
            index=models.Index(fields=['analysis', 'warning_type'], name='medication__analysi_5c7fbf_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['owner', 'active_ingredient'], name='medication__owner_i_9d738a_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['analysis', 'duplicate_key'], name='medication__analysi_77b143_idx'),
        ),
    ]
