# Generated by Django 5.2.16 on 2026-07-11 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='requested', max_length=32)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('health_status', models.CharField(choices=[('good', 'Good'), ('needs_attention', 'Needs Attention'), ('critical', 'Critical')], default='good', max_length=32)),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('food_guidance', models.JSONField(blank=True, default=list)),
                ('lifestyle_guidance', models.JSONField(blank=True, default=list)),
                ('doctor_prompts', models.JSONField(blank=True, default=list)),
                ('disclaimer', models.TextField(blank=True)),
                ('safety_review_required', models.BooleanField(default=False)),
                ('safety_review_notes', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='report-analysis-v1', max_length=40)),
                ('source_document_reference', models.CharField(blank=True, max_length=255)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analyses', to='documents.medicaldocument')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiomarkerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('value', models.CharField(max_length=80)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('normal_range', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('severity', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('explanations', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers', to='report_analysis.reportanalysis')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='reportanalysis',
            index=models.Index(fields=['owner', 'status'], name='report_anal_owner_i_457b32_idx'),
        ),
        migrations.AddIndex(
            model_name='reportanalysis',
            index=models.Index(fields=['owner', 'health_status'], name='report_anal_owner_i_544daf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportanalysis',
            index=models.Index(fields=['document', 'created_at'], name='report_anal_documen_d5ac47_idx'),
        ),
        migrations.AddIndex(
            model_name='biomarkerresult',
            index=models.Index(fields=['analysis', 'status'], name='report_anal_analysi_e0f0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='biomarkerresult',
            index=models.Index(fields=['analysis', 'severity'], name='report_anal_analysi_27a9d0_idx'),
        ),
    ]
