# Generated by Django 5.2.16 on 2026-07-11 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('energy', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('pain', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('fever_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_sugar_mg_dl', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('water_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'entry_date'], name='daily_healt_owner_i_6af7eb_idx'), models.Index(fields=['owner', 'mood'], name='daily_healt_owner_i_9cc02a_idx'), models.Index(fields=['owner', 'stress'], name='daily_healt_owner_i_977846_idx')],
            },
        ),
        migrations.CreateModel(
            name='LifestylePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('diet', 'Diet'), ('exercise', 'Exercise')], max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('restrictions', models.JSONField(blank=True, default=list)),
                ('doctor_consultation_prompts', models.JSONField(blank=True, default=list)),
                ('safety_notes', models.JSONField(blank=True, default=list)),
                ('input_context', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='lifestyle-planner-v1', max_length=40)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['owner', 'plan_type'], name='daily_healt_owner_i_aa48ca_idx'), models.Index(fields=['owner', 'generated_at'], name='daily_healt_owner_i_0282d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=160)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=32)),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('doctor_consultation_recommended', models.BooleanField(default=False)),
                ('safety_notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['owner', 'started_at'], name='daily_healt_owner_i_cee592_idx'), models.Index(fields=['owner', 'severity'], name='daily_healt_owner_i_1f305c_idx'), models.Index(fields=['owner', 'symptom'], name='daily_healt_owner_i_1c73ec_idx')],
            },
        ),
    ]
