# Generated by Django 5.2.16 on 2026-07-11 17:43

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_family_circles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('parent', 'Parent'), ('child', 'Child'), ('doctor', 'Doctor'), ('caregiver', 'Caregiver'), ('emergency_contact', 'Emergency Contact')], max_length=32)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='invited', max_length=32)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family_care.familycircle')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_family_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=80, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='family_care.familycircle')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='family_care.familymembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_access_events', to=settings.AUTH_USER_MODEL)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='family_care.familycircle')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='family_care.familymembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('profile', 'Profile'), ('reports', 'Reports'), ('trends', 'Trends'), ('medications', 'Medications'), ('symptoms', 'Symptoms'), ('journal', 'Journal'), ('doctor_summary', 'Doctor Summary'), ('emergency_profile', 'Emergency Profile')], max_length=40)),
                ('is_allowed', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_permission_grants', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='family_care.familymembership')),
            ],
            options={
                'ordering': ['permission'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('summary_payload', models.JSONField(default=dict)),
                ('questions_for_doctor', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='doctor-summary-v1', max_length=40)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['owner', 'generated_at'], name='family_care_owner_i_49f9e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyProfileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Emergency profile', max_length=180)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=80, unique=True)),
                ('qr_payload', models.JSONField(blank=True, default=dict)),
                ('profile_payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_profile_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='family_care_owner_i_142277_idx'), models.Index(fields=['token', 'is_active'], name='family_care_token_c11430_idx'), models.Index(fields=['expires_at', 'is_active'], name='family_care_expires_cb9829_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='familycircle',
            index=models.Index(fields=['owner', 'is_active'], name='family_care_owner_i_8fe640_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['circle', 'role'], name='family_care_circle__dd9481_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['circle', 'status'], name='family_care_circle__437b63_idx'),
        ),
        migrations.AddIndex(
            model_name='familymembership',
            index=models.Index(fields=['email', 'status'], name='family_care_email_136c93_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['token', 'status'], name='family_care_token_be3368_idx'),
        ),
        migrations.AddIndex(
            model_name='familyinvitation',
            index=models.Index(fields=['circle', 'status'], name='family_care_circle__ba6896_idx'),
        ),
        migrations.AddIndex(
            model_name='familyaccessaudit',
            index=models.Index(fields=['circle', 'created_at'], name='family_care_circle__0fbc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='familyaccessaudit',
            index=models.Index(fields=['actor', 'created_at'], name='family_care_actor_i_143433_idx'),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.UniqueConstraint(fields=('membership', 'permission'), name='unique_membership_permission'),
        ),
    ]
